conntrack: make sure counters is set
Avoid error like:

  File "/usr/lib/python3.11/site-packages/nethsec/conntrack/__init__.py", line 39, in __parse_meta_connection_tag
    result['packets'] = counters.find('packets').text
                        ^^^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'find'