conntrack: make sure counters is set (#67)
Avoid error like:

  File "/usr/lib/python3.11/site-packages/nethsec/conntrack/__init__.py", line 39, in __parse_meta_connection_tag
    result['packets'] = counters.find('packets').text
                        ^^^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'find'

The error could be caused by a connection like this one

  unknown  2 598 src=0.0.0.0 dst=224.0.0.1 [UNREPLIED] src=224.0.0.1 dst=0.0.0.0 mark=0 use=1